### ISSUE TITLE
Realse new version supporting faraday v2

### ISSUE THREAD

**Issue by bonias-jt** [AlexWayfer/faraday-encode_xml#34]
Hi!

Is it possible to release a new version supporting Faraday v2? (including https://github.com/AlexWayfer/faraday-encode_xml/pull/21)

**Comment by AlexWayfer** [comment]
Hello.

Thank you for reminder and sorry for a late response.

Yes, of course it's possible.

I've made some minor improvements (generally for CI and development process) and have published 1.0 version.

Enjoy!
